// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
	"time"
)

type Job struct {
	ID           int64          `json:"id"`
	Status       string         `json:"status"`
	S3Key        string         `json:"s3_key"`
	UploadUrl    string         `json:"upload_url"`
	ResultUrl    sql.NullString `json:"result_url"`
	LogosFound   sql.NullString `json:"logos_found"`
	ErrorMessage sql.NullString `json:"error_message"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
	CompletedAt  time.Time      `json:"completed_at"`
}

type Logo struct {
	ID          int64     `json:"id"`
	JobID       int64     `json:"job_id"`
	BoundingBox string    `json:"bounding_box"`
	Confidence  int64     `json:"confidence"`
	LogoType    string    `json:"logo_type"`
	S3Key       string    `json:"s3_key"`
	CreatedAt   time.Time `json:"created_at"`
}
