// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"
)

type Querier interface {
	CreateJob(ctx context.Context, arg CreateJobParams) (Job, error)
	CreateLogo(ctx context.Context, arg CreateLogoParams) (Logo, error)
	DeleteJob(ctx context.Context, id int64) error
	GetJob(ctx context.Context, id int64) (Job, error)
	GetLogosByJobID(ctx context.Context, jobID int64) ([]Logo, error)
	ListJobs(ctx context.Context, arg ListJobsParams) ([]Job, error)
	UpdateJobCompleted(ctx context.Context, arg UpdateJobCompletedParams) (Job, error)
	UpdateJobError(ctx context.Context, arg UpdateJobErrorParams) (Job, error)
	UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) (Job, error)
}

var _ Querier = (*Queries)(nil)
